sudo: required

# Travis doesn't provide a wide variety of host environments to run on, so we
# rely on Docker to provide these instead.
services:
  - docker

# It is not really needed, other than for showing correct language tag in
# Travis CI build log.
language: c

# The matrix of targets that we're interested in.
env:
  - HOST="ubuntu:16.04"
  - HOST="ubuntu:16.04" RISCV_CFLAGS="-std=c99 -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter"

# Before running the install phase we need to set up docker container that runs
# the target machine.
before_install:
# Spin up container
  - docker run -d --name host -v $(pwd):/travis $HOST tail -f /dev/null
  - docker ps

# Update the container and install dependencies
install:
  - docker exec -t host bash -c "yes | apt-get update"
  - docker exec -t host bash -c "yes | apt-get upgrade"
  - docker exec -t host bash -c "yes | apt-get install build-essential git wget"
# Download RISC-V embedded toolchain
  - docker exec -t host bash -c "cd /travis && wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.2.0-2019.05.3-x86_64-linux-ubuntu14.tar.gz"
  - docker exec -t host bash -c "cd /travis && tar xzvf riscv64-unknown-elf-gcc-8.2.0-2019.05.3-x86_64-linux-ubuntu14.tar.gz"

# Here's where we actually run the test.
script:
# Build all software for all targets
  - docker exec -t host bash -c "export RISCV_PATH=/travis/riscv64-unknown-elf-gcc-8.2.0-2019.05.3-x86_64-linux-ubuntu14 && cd /travis && RISCV_CFLAGS=\"$RISCV_CFLAGS\" ./scripts/all-targets-build"
